Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Janusz Optimizer Siódmy eta-redukował małe funkcje
  allowed_mime:
      - audio/mpeg
      - audio/flac
      - audio/mp3
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
